version: "3"
services:
  selenium-hub:
    image: selenium/hub:4.34.0
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome-node:
    image: selenium/node-chrome:4.34.0
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-grid

  firefox-node:
    image: selenium/node-firefox:4.34.0
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-grid

  orangehrm:
    image: orangehrm/orangehrm
    container_name: orangehrm
    ports:
      - "8080:8080"
    networks:
      - selenium-grid

networks:
  selenium-grid:
    driver: bridge
